networks:
  idnet:
    name: idnet

services: 
  backend:
    image: ahmadck/id:latest
    container_name: IDServer
    ports:
      - "5000:80"
      - "5001:81"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PG=Server=database;Port=5432;Database=postgres;User Id=postgres;Password=postgres;
    networks:
      - idnet
    depends_on:
      - database
    restart: on-failure


  database:
    image: postgres:latest
    container_name: DB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - idnet

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - idnet